version: "3.8"

services:
  frontend:
    platform: linux/x86_64
    image: peilunnn/online-store-frontend
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"

  backend:
    platform: linux/x86_64
    image: peilunnn/online-store-backend
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8000:8000"
